name: Upload to GCS

on:
  push:
    branches:
      - main

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Setup gcloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "pvnkn3t" # Replace with your actual project ID
          install_components: storage

      # Upload files to GCS
      - name: Upload to GCS
        run: |
          gsutil -m rsync -r . gs://pvnkn3t-repo-sync
